# Schema for the configuration files of the word_counter module.

word_counter.settings:
  type: config_object
  label: 'Word Counter settings'
  mapping:
    status:
      type: boolean
      label: 'Activate feature'
